### ISSUE TITLE
GUI Test segfaults on exit but works

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#206]

**Comment by EternalWind** [comment]
Details?

**Comment by svenstaro** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4d5f699 in MyGUI::WidgetInput::~WidgetInput() () from /usr/lib/libMyGUIEngine.so.3
(gdb) bt
#0  0x00007ffff4d5f699 in MyGUI::WidgetInput::~WidgetInput() () from /usr/lib/libMyGUIEngine.so.3
#1  0x00007ffff4d31a17 in MyGUI::Widget::~Widget() () from /usr/lib/libMyGUIEngine.so.3
#2  0x00007ffff4cc6fc6 in MyGUI::Button::~Button() () from /usr/lib/libMyGUIEngine.so.3
#3  0x00007ffff4deda6e in MyGUI::WidgetManager::_deleteDelayWidgets() () from /usr/lib/libMyGUIEngine.so.3
#4  0x00007ffff4dee72e in MyGUI::WidgetManager::shutdown() () from /usr/lib/libMyGUIEngine.so.3
#5  0x00007ffff4da8794 in MyGUI::Gui::shutdown() () from /usr/lib/libMyGUIEngine.so.3
#6  0x00007ffff7b1bb00 in dt::GuiManager::deinitialize (this=0x707dc8)
    at /home/svenstaro/prj/ducttape-engine/engine/src/Gui/GuiManager.cpp:66
#7  0x00007ffff7b30423 in dt::DisplayManager::_destroyWindow (this=0x707d60)
    at /home/svenstaro/prj/ducttape-engine/engine/src/Graphics/DisplayManager.cpp:136
#8  0x00007ffff7b2f8a5 in dt::DisplayManager::deinitialize (this=0x707d60)
    at /home/svenstaro/prj/ducttape-engine/engine/src/Graphics/DisplayManager.cpp:33
#9  0x00007ffff7ae1962 in dt::Root::deinitialize (this=0x7ffff7dd8e00)
    at /home/svenstaro/prj/ducttape-engine/engine/src/Core/Root.cpp:89
#10 0x00007ffff7add875 in dt::Game::run (this=0x7fffffffe090, start_state=0x70f720, argc=2, 
    argv=0x7fffffffe348) at /home/svenstaro/prj/ducttape-engine/engine/src/Scene/Game.cpp:108
#11 0x0000000000438b2f in GuiTest::GuiTest::run (this=0x6db9f0, argc=2, argv=0x7fffffffe348)
    at /home/svenstaro/prj/ducttape-engine/tests/src/GuiTest/GuiTest.cpp:20
#12 0x000000000045549f in main (argc=2, argv=0x7fffffffe348)
    at /home/svenstaro/prj/ducttape-engine/tests/src/TestFramework.cpp:120

**Comment by LeviSchuck** [comment]
Usually something is being deleted in the wrong order here.

**Comment by EternalWind** [comment]
I got no error though...
